site_name: REL
site_description: Modern Database Access Layer for Golang - Testable, Extendable and Crafted Into a Clean and Elegant API
site_author: REL
site_url: https://go-rel.github.io/
repo_url: https://github.com/go-rel/rel
repo_name: go-rel/rel

nav:
  - Home: index.md
  - Getting Started:
    - Introduction: introduction.md
    - Basics: basics.md
    - Reading and Writing Record: crud.md
    - Queries: queries.md
    - Mutations: mutations.md
    - Association: association.md
    - Transactions: transactions.md
    - Migration: migration.md
    - Instrumentation: instrumentation.md
  - Reference:
    - github.com/go-rel/rel: reference/rel.md
    - github.com/go-rel/rel/group: reference/group.md
    - github.com/go-rel/rel/join: reference/join.md
    - github.com/go-rel/rel/migrator: reference/migrator.md
    - github.com/go-rel/rel/reltest: reference/reltest.md
    - github.com/go-rel/rel/sort: reference/sort.md
    - github.com/go-rel/rel/where: reference/where.md
    - github.com/go-rel/rel/adapter/mysql: reference/adapter-mysql.md
    - github.com/go-rel/rel/adapter/postgres: reference/adapter-postgres.md
    - github.com/go-rel/rel/adapter/sql: reference/adapter-sql.md
    - github.com/go-rel/rel/adapter/sqlite3: reference/adapter-sqlite3.md
  - Adapters:
    - Adapters: adapters.md
  - Changelog:
    - Release Notes: changelog/release-notes.md

theme:
  name: material
  favicon: static/favicon.png
  icon:
    logo: material/database
  palette:
    primary: light blue
    accent: green
  features:
    - tabs
  custom_dir: docs/overrides
  
plugins:
  - search
  - git-revision-date
  - macros:
      module_name: docs/main
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: go-rel
      repo: rel

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/go-rel
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Fs02

google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
