name: Publish docs
on:
  push:
    # branches:
    #   - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install mkdocs and it's plugins
        run: |
          pip install \
            mkdocs>=1.1 \
            Pygments>=2.4 \
            markdown>=3.2 \
            pymdown-extensions>=7.0 \
            mkdocs-material-extensions>=1.0 \
            mkdocs-minify-plugin>=0.3 \
            mkdocs-redirects>=1.0 \
            mkdocs-macros-plugin \
            mkdocs-git-revision-date-plugin \
            requests
      - name: Install godoc2md
        run: go get github.com/davecheney/godoc2md
      - name: Build docs
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          ls
          echo "\n"
          ls docs
          mkdocs --version
          mkdocs build
      - name: Deploy docs
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /site
          dst_path: /.
          dst_owner: go-rel
          dst_repo_name: go-rel.github.io
