name: Publish docs
on:
  push:
    # branches:
    #   - master


defaults:
  run:
    working-directory: rel

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: rel
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install mkdocs and it's plugins
        run: |
          pip install \
            requests \
            mkdocs \
            mkdocs-material-extensions \
            mkdocs-minify-plugin \
            mkdocs-macros-plugin \
            mkdocs-git-revision-date-plugin
      - name: Install godoc2md
        run: go get github.com/davecheney/godoc2md
      - name: Build docs
        working-directory: ./rel
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs --version
          mkdocs build
      - name: Push site
        uses: actions/checkout@v2
        with:
          repository: go-rel/go-rel.github.io
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: go-rel.github.io
        run: |
          yes | cp -rf ../rel/site/* .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
